# Generated by Django 3.2.5 on 2021-09-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_content_rating', models.IntegerField(blank=True, null=True)),
                ('future_event', models.TextField(blank=True, null=True)),
                ('is_attending', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
