# Generated by Django 3.2.7 on 2021-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestions',
            name='educational_content_rating',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], null=True),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='is_attending',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No', 'no')], max_length=3, null=True),
        ),
    ]
